/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

/*
 * @author Brand
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    Ingresar i;
    public Interfaz() {
        initComponents();
        i =new Ingresar();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ValorC = new javax.swing.JTextField();
        ValorCh = new javax.swing.JTextField();
        ValorSP = new javax.swing.JTextField();
        ValorSSA = new javax.swing.JTextField();
        ValorSR = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ValorJ = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        IngProducto = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        TotalQ = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        FaltaQ = new javax.swing.JTextField();
        TotalC = new javax.swing.JTextField();
        TotalCh = new javax.swing.JTextField();
        TotalSP = new javax.swing.JTextField();
        TotalSSA = new javax.swing.JTextField();
        TotalSR = new javax.swing.JTextField();
        TotalJ = new javax.swing.JTextField();
        FaltaC = new javax.swing.JTextField();
        FaltaCh = new javax.swing.JTextField();
        FaltaSP = new javax.swing.JTextField();
        FaltaSSA = new javax.swing.JTextField();
        FaltaSR = new javax.swing.JTextField();
        FaltaJ = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ValorQ = new javax.swing.JTextField();
        RevFalt = new javax.swing.JButton();
        JLimp = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        EspQ = new javax.swing.JTextField();
        EspC = new javax.swing.JTextField();
        EspCh = new javax.swing.JTextField();
        EspSP = new javax.swing.JTextField();
        EspSSA = new javax.swing.JTextField();
        EspSR = new javax.swing.JTextField();
        EspJ = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));
        setMinimumSize(new java.awt.Dimension(600, 350));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cantidad de queso");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, -1));

        jLabel2.setText("Cantidad de crema");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setText("Cantidad de Chorizo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel4.setText("Cantidad de S Pavo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel5.setText("Cantidad de S SA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel6.setText("Cantidad de S Ross");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        ValorC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorCActionPerformed(evt);
            }
        });
        getContentPane().add(ValorC, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 86, -1));
        getContentPane().add(ValorCh, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 86, -1));
        getContentPane().add(ValorSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 86, -1));
        getContentPane().add(ValorSSA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 86, -1));
        getContentPane().add(ValorSR, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 86, -1));

        jLabel7.setText("Cantidad Jamon");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));
        getContentPane().add(ValorJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 86, -1));

        jLabel8.setText("Kilos (kg)");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        IngProducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        IngProducto.setText("Ingresar producto");
        IngProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngProductoActionPerformed(evt);
            }
        });
        getContentPane().add(IngProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, 30));

        jLabel9.setText("Total");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        TotalQ.setEditable(false);
        getContentPane().add(TotalQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 78, -1));

        jLabel10.setText("Faltan");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        FaltaQ.setEditable(false);
        getContentPane().add(FaltaQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 79, -1));

        TotalC.setEditable(false);
        getContentPane().add(TotalC, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 78, -1));

        TotalCh.setEditable(false);
        getContentPane().add(TotalCh, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 78, -1));

        TotalSP.setEditable(false);
        getContentPane().add(TotalSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 78, -1));

        TotalSSA.setEditable(false);
        getContentPane().add(TotalSSA, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 78, -1));

        TotalSR.setEditable(false);
        getContentPane().add(TotalSR, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 78, -1));

        TotalJ.setEditable(false);
        getContentPane().add(TotalJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 78, -1));

        FaltaC.setEditable(false);
        getContentPane().add(FaltaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 79, -1));

        FaltaCh.setEditable(false);
        getContentPane().add(FaltaCh, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 79, -1));

        FaltaSP.setEditable(false);
        getContentPane().add(FaltaSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 79, -1));

        FaltaSSA.setEditable(false);
        getContentPane().add(FaltaSSA, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 79, -1));

        FaltaSR.setEditable(false);
        FaltaSR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FaltaSRActionPerformed(evt);
            }
        });
        getContentPane().add(FaltaSR, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 79, -1));

        FaltaJ.setEditable(false);
        getContentPane().add(FaltaJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 79, -1));

        jLabel12.setBackground(new java.awt.Color(0, 204, 204));
        jLabel12.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel12.setText("Cremeria \"La Q'Sabrosa\"");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        ValorQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorQActionPerformed(evt);
            }
        });
        getContentPane().add(ValorQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 90, -1));

        RevFalt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RevFalt.setText("Revisar faltantes");
        RevFalt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RevFaltActionPerformed(evt);
            }
        });
        getContentPane().add(RevFalt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 160, 30));

        JLimp.setBackground(new java.awt.Color(255, 0, 0));
        JLimp.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 24)); // NOI18N
        JLimp.setForeground(new java.awt.Color(255, 255, 255));
        JLimp.setText("Limpiar");
        JLimp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JLimpActionPerformed(evt);
            }
        });
        getContentPane().add(JLimp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, 40));

        jLabel11.setText("Esperado");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));
        getContentPane().add(EspQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 50, 70, -1));
        getContentPane().add(EspC, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 90, 70, -1));
        getContentPane().add(EspCh, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 130, 70, -1));
        getContentPane().add(EspSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 170, 70, -1));
        getContentPane().add(EspSSA, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 200, 70, -1));
        getContentPane().add(EspSR, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 240, 70, -1));
        getContentPane().add(EspJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 280, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ValorCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorCActionPerformed

    private void IngProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngProductoActionPerformed
        i.setEqueso(Double.parseDouble(EspQ.getText()));
        i.setEcrema(Double.parseDouble(EspC.getText()));
        i.setEchorizo(Double.parseDouble(EspCh.getText()));
        i.setEsalchichaP(Double.parseDouble(EspSP.getText()));
        i.setEsalchichaSA(Double.parseDouble(EspSSA.getText()));
        i.setEsalchichaR(Double.parseDouble(EspSR.getText()));
        i.setEjamon(Double.parseDouble(EspJ.getText()));
        
        EspQ.setText(String.valueOf(i.getEqueso()));
        EspC.setText(String.valueOf(i.getEcrema()));
        EspCh.setText(String.valueOf(i.getEchorizo()));
        EspSP.setText(String.valueOf(i.getEsalchichaP()));
        EspSSA.setText(String.valueOf(i.getEsalchichaSA()));
        EspSR.setText(String.valueOf(i.getEsalchichaR()));
        EspJ.setText(String.valueOf(i.getEjamon()));
        
        i.setQueso(Double.parseDouble(ValorQ.getText()));
        i.SumarQ();
        TotalQ.setText(String.valueOf(i.getTqueso()));
        
        i.setCrema(Double.parseDouble(ValorC.getText()));
        i.SumarC();
        TotalC.setText(String.valueOf(i.getTcrema()));
        
        i.setChorizo(Double.parseDouble(ValorCh.getText()));
        i.SumarCh();
        TotalCh.setText(String.valueOf(i.getTchorizo()));
        
        i.setSalchichaP(Double.parseDouble(ValorSP.getText()));
        i.SumarSP();
        TotalSP.setText(String.valueOf(i.getTsalchichaP()));
        
        i.setSalchichaSA(Double.parseDouble(ValorSSA.getText()));
        i.SumarSSA();
        TotalSSA.setText(String.valueOf(i.getTsalchichaSA()));
        
        i.setSalchichaR(Double.parseDouble(ValorSR.getText()));
        i.SumarSR();
        TotalSR.setText(String.valueOf(i.getTsalchichaR()));
        
        i.setJamon(Double.parseDouble(ValorJ.getText()));
        i.SumarJ();
        TotalJ.setText(String.valueOf(i.getTjamon()));
        
        /*i.setTqueso(Double.parseDouble(TotalQ.getText()));
        i.RestaQ();
        FaltaQ.setText(String.valueOf(i.getRqueso()));
        
        
        i.setTcrema(Double.parseDouble(TotalC.getText()));
        i.RestaC();
        FaltaC.setText(String.valueOf(i.getRcrema()));
        
        i.setTchorizo(Double.parseDouble(TotalCh.getText()));
        i.RestaCh();
        FaltaCh.setText(String.valueOf(i.getRchorizo()));
        
        i.setTsalchichaP(Double.parseDouble(TotalSP.getText()));
        i.RestaSP();
        FaltaSP.setText(String.valueOf(i.getRsalchichaP()));
        
        i.setTsalchichaSA(Double.parseDouble(TotalSSA.getText()));
        i.RestaSSA();
        FaltaSSA.setText(String.valueOf(i.getRsalchichaSA()));
        
        i.setTsalchichaR(Double.parseDouble(TotalSR.getText()));
        i.RestaSR();
        FaltaSR.setText(String.valueOf(i.getRsalchichaR()));
        
        i.setTjamon(Double.parseDouble(TotalJ.getText()));
        i.RestaJ();
        FaltaJ.setText(String.valueOf(i.getRjamon()));*/
    }//GEN-LAST:event_IngProductoActionPerformed

    private void FaltaSRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FaltaSRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FaltaSRActionPerformed

    private void ValorQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorQActionPerformed
            }//GEN-LAST:event_ValorQActionPerformed

    private void RevFaltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RevFaltActionPerformed
        i.setTqueso(Double.parseDouble(TotalQ.getText()));
        i.RestaQ();
        FaltaQ.setText(String.valueOf(i.getRqueso()));
        
        
        i.setTcrema(Double.parseDouble(TotalC.getText()));
        i.RestaC();
        FaltaC.setText(String.valueOf(i.getRcrema()));
        
        i.setTchorizo(Double.parseDouble(TotalCh.getText()));
        i.RestaCh();
        FaltaCh.setText(String.valueOf(i.getRchorizo()));
        
        i.setTsalchichaP(Double.parseDouble(TotalSP.getText()));
        i.RestaSP();
        FaltaSP.setText(String.valueOf(i.getRsalchichaP()));
        
        i.setTsalchichaSA(Double.parseDouble(TotalSSA.getText()));
        i.RestaSSA();
        FaltaSSA.setText(String.valueOf(i.getRsalchichaSA()));
        
        i.setTsalchichaR(Double.parseDouble(TotalSR.getText()));
        i.RestaSR();
        FaltaSR.setText(String.valueOf(i.getRsalchichaR()));
        
        i.setTjamon(Double.parseDouble(TotalJ.getText()));
        i.RestaJ();
        FaltaJ.setText(String.valueOf(i.getRjamon()));
    }//GEN-LAST:event_RevFaltActionPerformed

    private void JLimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JLimpActionPerformed
        ValorQ.setText(String.valueOf("0"));
        ValorC.setText(String.valueOf("0"));
        ValorCh.setText(String.valueOf("0"));
        ValorSP.setText(String.valueOf("0"));
        ValorSSA.setText(String.valueOf("0"));
        ValorSR.setText(String.valueOf("0"));
        ValorJ.setText(String.valueOf("0"));
    }//GEN-LAST:event_JLimpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EspC;
    private javax.swing.JTextField EspCh;
    private javax.swing.JTextField EspJ;
    private javax.swing.JTextField EspQ;
    private javax.swing.JTextField EspSP;
    private javax.swing.JTextField EspSR;
    private javax.swing.JTextField EspSSA;
    private javax.swing.JTextField FaltaC;
    private javax.swing.JTextField FaltaCh;
    private javax.swing.JTextField FaltaJ;
    private javax.swing.JTextField FaltaQ;
    private javax.swing.JTextField FaltaSP;
    private javax.swing.JTextField FaltaSR;
    private javax.swing.JTextField FaltaSSA;
    private javax.swing.JButton IngProducto;
    private javax.swing.JButton JLimp;
    private javax.swing.JButton RevFalt;
    private javax.swing.JTextField TotalC;
    private javax.swing.JTextField TotalCh;
    private javax.swing.JTextField TotalJ;
    private javax.swing.JTextField TotalQ;
    private javax.swing.JTextField TotalSP;
    private javax.swing.JTextField TotalSR;
    private javax.swing.JTextField TotalSSA;
    private javax.swing.JTextField ValorC;
    private javax.swing.JTextField ValorCh;
    private javax.swing.JTextField ValorJ;
    private javax.swing.JTextField ValorQ;
    private javax.swing.JTextField ValorSP;
    private javax.swing.JTextField ValorSR;
    private javax.swing.JTextField ValorSSA;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

/*    private int queso;
    private int chorizo;
    private int crema;
    private int salchichap;
    private int salchichasa;
    private int salchichar;
    private int jamon;
    private int rqueso;
    private int rchorizo;
    private int rcrema;
    private int rsalchichap;
    private int rsalchichasa;
    private int rsalchichar;
    private int rjamon;
    private int tqueso;
    private int tchorizo;
    private int tcrema;
    private int tsalchichap;
    private int tsalchichasa;
    private int tsalchichar;
    private int tjamon;
    
    public void setQueso(int ValorQ){
        this.queso = ValorQ;}
    public void setCrema(int ValorC){
        this.crema = ValorC;}
    public void setChorizo(int ValorCh){
        this.chorizo = ValorCh;}
    public void setSalchichaP(int ValorSP){
        this.salchichap = ValorSP;}
    public void setSalchichaSA(int ValorSSA){
        this.salchichasa = ValorSSA;}
    public void setSalchichaR(int ValorSR){
        this.salchichar = ValorSR;}
    public void setJamon(int ValorJ){
        this.jamon = ValorJ;}
    
    public void setTqueso(int TotalQ){
        this.tqueso = TotalQ;}
    public void setTcrema(int TotalC){
        this.tcrema = TotalC;}
    public void setTchorizo(int TotalCh){
        this.tchorizo = TotalCh;}
    public void setTsalchichaP(int TotalSP){
        this.tsalchichap = TotalSP;}
    public void setTsalchichaSA(int TotalSSA){
        this.tsalchichasa = TotalSSA;}
    public void setTsalchichaR(int TotalSR){
        this.tsalchichar = TotalSR;}
    public void setTjamon(int TotalJ){
        this.tjamon = TotalJ;}
    
    public void setRqueso(int FaltaQ){
        this.rqueso = FaltaQ;}
    public void setRcrema(int FaltaC){
        this.rcrema = FaltaC;}
    public void setRchorizo(int FaltaCh){
        this.rchorizo = FaltaCh;}
    public void setRsalchichaP(int FaltaSP){
        this.rsalchichap = FaltaSP;}
    public void setRsalchichaSA(int FaltaSSA){
        this.rsalchichasa = FaltaSSA;}
    public void setRsalchichaR(int FaltaSR){
        this.rsalchichar = FaltaSR;}
    public void setRjamon(int FaltaJ){
        this.rjamon = FaltaJ;}
    
    public int getQueso(){
        return this.queso;}
    public int getCrema(){
        return this.crema;}
    public int getChorizo(){
        return this.chorizo;}
    public int getSalchichaP(){
        return this.salchichap;}
    public int getSalchichaSA(){
        return this.salchichasa;}
    public int getSalchichaR(){
        return this.salchichar;}
    public int getJamon(){
        return this.jamon;}
    
    public int getTqueso(){
        return this.tqueso;}
    public int getTcrema(){
        return this.tcrema;}
    public int getTchorizo(){
        return this.tchorizo;}
    public int getTsalchichaP(){
        return this.tsalchichap;}
    public int getTsalchichaSA(){
        return this.tsalchichasa;}
    public int getTsalchichaR(){
        return this.tsalchichar;}
    public int getTjamon(){
        return this.tjamon;}
    
    public int getRqueso(){
        return this.rqueso;}
    public int getRcrema(){
        return this.rcrema;}
    public int getRchorizo(){
        return this.rchorizo;}
    public int getRsalchichaP(){
        return this.rsalchichap;}
    public int getRsalchichaSA(){
        return this.rsalchichasa;}
    public int getRsalchichaR(){
        return this.rsalchichar;}
    public int getRjamon(){
        return this.rjamon;}
    
    private void SumarQ() {
       this.tqueso = (this.tqueso + this.queso);
    }

    private void SumarC() {
        this.tcrema = (this.tcrema + this.crema);
    }

    private void SumarCh() {
        this.tchorizo = (this.tchorizo + this.chorizo);    }

    private void SumarSP() {
        this.tsalchichap = (this.tsalchichap + this.salchichap);}

    private void SumarSSA() {
        this.tsalchichasa = (this.tsalchichasa + this.salchichasa);    }

    private void SumarSR() {
        this.tsalchichar = (this.tsalchichar + this.salchichar);    }

    private void SumarJ() {
        this.tjamon = (this.tjamon + this.jamon);    }
    
    public void RestaQ(){
        this.rqueso = (80 - this.tqueso);}
    
    public void RestaC(){
        this.rcrema = (100 - this.tcrema );}
    
    public void RestaCh(){
        this.rchorizo = (56 - this.tchorizo);}
    
    public void RestaSP(){
        this.rsalchichap = (40 - this.tsalchichap);}
    
    public void RestaSSA(){
        this.rsalchichasa = (34 - this.tsalchichasa);}
    
    public void RestaSR(){
        this.rsalchichar = (24 - this.tsalchichar);}
    
    public void RestaJ(){
        this.rjamon = (50 - this.tjamon);}*/
    
}
